import type { DataSource } from '@/types/datasource.interface'

export default async function fetchInterestGroups(): Promise<DataSource[]> {
  const interestGroups = [
    {
      uuid_interestGroup: 'rda_graph:8485631B',
      title: 'Active Data Management Plans IG',
      description:
        'The proposed activity of this group is to act as a nucleus for discussing requirements for and identifying developments needed to support active (i.e. able to evolve and be monitored) data management planning. Working groups will be proposed to carry out work on specific areas of interest.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/active-data-management-plans/activity/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:5C74BAF4',
      title: 'Archives and Records Professionals for Research Data IG',
      description:
        'The objective of this group is to provide a welcoming space for archivists and records management professionals within RDA to share knowledge and explore issues related to research data that arise in their professional activities. We explore the areas where the principles and practices in the information disciplines of archives, records management, and research data curation overlap and where they diverge. Examining alignments in theoretical frameworks, practical implementations, and goals among these information disciplines, we determine areas where practitioners across them can learn from each other in ways that can lead to the development of a vibrant community of information professionals working across different domains.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/archives-records-professionals-for-research-data/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00077482',
      title: 'Big Data IG',
      description:
        'The ultimate goal of RDA Big Data Interest Group is to produce a set of recommendation documents to advise diverse research communities with respect to: How to select an appropriate Big Data solution for a particular science application with optimal value? And what are the best practices in dealing with various data and computing issues associated with such a solution?',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/big-data-analytics-ig/activity/',
      status: 'Recognised & Endorsed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:FD931A77',
      title: 'Biodiversity Data Integration IG',
      description:
        'Disciplinary groups play a pivotal role in the RDA ecosystem. Not only do they provide a mechanism for engaging with the outputs of the RDA community, they are instrumental in providing input to the cross-cutting technical and socio-cultural groups. With its formation in 2013, the Biodiversity Data Integration IG has been one of the pioneering groups in RDA, focusing from the outset on linking the wider communities of practice in the biodiversity data domain with experts and other communities within RDA.',
      uuid_domain: '51DE8B93; D17D26A9',
      domains: 'Earth and related environmental sciences; Biological sciences',
      url: 'https://www.rd-alliance.org/groups/biodiversity-data-integration-ig/activity/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00049977',
      title: 'Chemistry Research Data IG',
      description:
        'We are proposing a Chemistry Research Data Interest Group under the auspices of the Research Data Alliance (RDA), to foster diverse professional exchange on issues particular to data originating from the field of chemistry. Chemistry, as one of the central sciences, has fundamental impact on the fields of health, pharmaceuticals, materials, energy and many other applied sciences. There is a wealth of chemical data in various heterogeneous formats, distributed across a myriad of systems with endless potential for reuse in chemistry research and many related domains. However, many social, technical and administrative factors have limited the opportunities for open sharing and interoperable exchange.',
      uuid_domain: 'D17D26A9',
      domains: 'Biological Sciences',
      url: 'https://www.rd-alliance.org/groups/chemistry-research-data-interest-group/activity/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00057521',
      title:
        'CODATA/RDA Research Data Science Schools for Low and Middle Income Countries',
      description:
        'This Interest Group will continue the work of the now completed RDA/CODATA Summer Schools in Data Science and Cloud Computing in the Developing World Working Group.',
      uuid_domain: '5CB3D8C8; C1E4C81A',
      domains: 'Computer and information sciences; Educational Sciences',
      url: 'https://www.rd-alliance.org/groups/codatarda-research-data-science-schools-low-and-middle-income-countries',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00000155',
      title: 'Community Capability Model IG',
      description:
        'The RDA Community Capability Model (CCM) Group collects, validates and publishes a range of data-centric “capability profiles” to enhance inter- and intra-domain interoperability and catalyse RDA data-sharing goals. Various barriers (technical, social, legal, ethical), currently make this difficult to achieve beyond established domain community boundaries, limiting the penetration and impact of data-intensive research. The CCM group also has potential to adopt a foundational role in synthesising outputs from other RDA Groups.',
      uuid_domain: '04DFE4A5; 5CB3D8C8',
      domains: 'Social Sciences; Computer and information sciences ',
      url: 'https://www.rd-alliance.org/groups/community-capability-model-ig/',
      status: 'Withdrawn',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00064476',
      title: 'Data Conservation IG',
      description:
        'Building on the work of the Data Rescue IG, the Data Conservation IG will both expand scope to all types of data (both digital and analog), and focus on decision-making topics including: How are data sets prioritized for rescue or conservation? How are risk factors defined, assessed, and/or categorized? How is funding prioritized and/or secured?',
      uuid_domain: '5CB3D8C8; 3CD09AF9',
      domains: 'Computer and information sciences; Economics and business',
      url: 'https://www.rd-alliance.org/groups/data-conservation-ig',
      status: 'Pending Submission',
      sub_status: 'Not yet endorsed',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00052248',
      title: 'Data Discovery Paradigms IG',
      description:
        'The objectives for this interest group are to provide a forum where representatives from across the spectrum of stakeholders and roles pertaining to data search can discuss issues related to improving data discovery. The goal is to deliver guidelines and recommendations that can be adopted by data repositories, infrastructure developers, data producers and data users to improve the discovery and use of research data.',
      uuid_domain: '5CB3D8C8; 5914EA8E',
      domains:
        'Computer and information sciences; Other engineering and technologies',
      url: 'https://www.rd-alliance.org/groups/data-discovery-paradigms-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00061534',
      title: 'Data Economics IG',
      description: 'Data Economics IG',
      uuid_domain: '3CD09AF9',
      domains: 'Economics and business',
      url: 'https://www.rd-alliance.org/groups/data-economics-ig',
      status: 'Not endorsed',
      sub_status: 'Not yet endorsed',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:922D9D64',
      title: 'Data for Development IG',
      description:
        'This interest group focuses on the access to and usage of data from a variety of sources of relevance to development studies, human rights, conflict research and vulnerable and hidden populations. Whereas many intergovernmental organizations have a tradition of open data access routines and policies to data they have collected, data collected by non-governmental organizations are often not available for further usage. Also relevant data collected by university institutes and research organizations are often not shared with the community and increasingly also the question is raised which contribution big data may have in this area and how to collect, use, share and analyze these data.',
      uuid_domain: '04DFE4A5; 95093901; 6DC9618F',
      domains: 'Social Sciences; Medical and Health Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/data-development/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00053666',
      title: 'Data Policy Standardisation and Implementation IG',
      description:
        'Increasing the availability of research data for reuse is in part being driven by research data policies and the number of funders and journals and institutions with some form of research data policy is growing. The research data policy landscape of funders, institutions and publishers is however too complex (Ref: http://insights.uksg.org/articles/10.1629/uksg.284/) and the implementation and implications of policies for researchers can be unclear. While around half of researchers share data, their primary motivations are often to carry out and publish good research, and to receive renewed funding, rather than making data available. Data policies that support publication of research need to be practical and seen in this context to be effective beyond specialist data communities and publications.',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social Science',
      url: 'https://www.rd-alliance.org/groups/data-policy-standardisation-and-implementation-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00044507',
      title: 'Data re-use, share your experiences',
      description:
        'That’s why we’d like to create an interest group on “data re-use” to give the opportunity to scientists to share their experiences, express their needs not in technical terms but from a user point of view. The interest group could help to (to be discussed) : identify data re-use use cases and practices, analyze those use cases : what works, what doesn\'t and why, create a directory of "success stories" to communicate, identify new technical problems to be addressed by the technical groups, identify the benefits, give a place to the scientist to express their needs',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/data-re-use-share-your-experiences',
      status: 'Withdrawn',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00047603',
      title: 'Data Rescue IG',
      description:
        'The objectives of the new IG will be (a) to ferret out and catalogue known data-rescue efforts as exemplars of what can be achieved, and thereby raising the profile of Data Rescue in the world at large, (b) to establish an advisory system for \'digitizing\' and associated tasks, and (c) to communicate with relevant RDA IGs (Education, Metadata, History & Ethnography, Long Tail of Data, and the domain-specific standard-setters). It will also consider extending its remit to \'adding value\' to older digital data. It will provide a unique forum for sharing experience, expertise and ideas. Its overarching goal will be to convince scientists and policy makers of the immense value of implementing data rescue, and by enabling interoperability, access and (thence) wide application, to grow the activity into an essential and routine element of all research.',
      uuid_domain: '2581C431',
      domains: 'Natural sciences',
      url: 'https://www.rd-alliance.org/groups/data-rescue/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00054345',
      title: 'Data Versioning IG',
      description:
        'The demand for reproducibility of research results and re-using data is growing, therefore it will become increasingly important for a researcher to be able to cite the exact version of the dataset that was used to underpin their research publication. The capacity of computational hardware infrastructures have grown and this has encouraged the development of concatenated seamless data sets where users can use web services to select subsets based on spatial and time queries, or other data attributes. Further, the growth in computer power has meant that higher-level data products can be generated in really short time frames. This means that we need a systematic way to refer to the exact version of a data set or data product that was used to underpin the research findings or was used to generate higher-level data products, including who developed and also funded it.',
      uuid_domain: '5CB3D8C8; 5914EA8E',
      domains:
        'Computer and information sciences; Other engineering and technologies',
      url: 'https://www.rd-alliance.org/groups/data-versioning-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:E86C9600',
      title: 'Digital Practices in History and Ethnography IG',
      description:
        'RDA’s Digital Practices in History and Ethnography Interest Group (DPHP-IG) works to advance data standards, practices and infrastructure for historical and ethnographic research, contributing to broader efforts in the digital humanities and social sciences.',
      uuid_domain: '0191D876; CD19AFF7; C0EB38D1',
      domains:
        'Philosophy, ethics and religion; Other humanities; History and archaeology',
      url: 'https://www.rd-alliance.org/groups/digital-practices-history-and-ethnography-ig/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00056566',
      title: 'Disciplinary Collaboration Framework IG',
      description:
        'We propose the formulation of an RDA Interest Group that will aim at bringing together representatives across disciplinary communities in an effort to better organise and drive the discussion for prioritising, harmonising and efficiently articulating communities’ needs. The group will gradually support the development of a common disciplinary interoperability framework.',
      uuid_domain: '04DFE4A5; 18792041; 285F97D3; 95093901; 27BE021B; 6DC9618F',
      domains:
        'Social Sciences; Natural Sciences; Engineering and Technology; Medical and Health Sciences; Agricultural Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/disciplinary-collaboration-framework-ig',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:DC190947',
      title: 'Domain Repositories IG',
      description:
        'The Domain Repositories Interest Group will bring together active data repositories that serve specific scientific disciplines. Domain repositories provide archiving services tailored to the needs of scientific communities, and they mediate between domain scientists and rapid changes in information and data science. All domain repositories have shared interests in data curation, dissemination, preservation, and institutional sustainability, and this interest group will provide a forum for sharing practical experience and developing joint projects. The IG will also develop training and mentoring relationships for new and emerging repositories.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/domain-repositories-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:2B48EB74',
      title: 'Early Career and Engagement IG',
      description:
        'The purpose of the Early Career and Engagement Interest Group (ECEIG) is to provide a focal point for Early and Mid-Career Researchers and Professionals, including those involved in various RDA-related fellowships and Early Career programs.',
      uuid_domain: 'C1E4C81A; 04DFE4A5',
      domains: 'Educational sciences; Social sciences',
      url: 'https://www.rd-alliance.org/groups/early-career-and-engagement-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:6A1A68A6',
      title: 'Education and Training on Handling of Research Data IG',
      description:
        'The objective of this IG is the exchange of information about existing developments and initiatives and promotion of training/education to manage research data throughout the data lifecycle. Concretely, it will make the case for creating taxonomies of the skills required by different group of data management specialists/professionals and elaborating reference models',
      uuid_domain: '5CB3D8C8; C1E4C81A',
      domains: 'Computer and information sciences; Educational Sciences',
      url: 'https://www.rd-alliance.org/groups/education-and-training-handling-research-data/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00066746',
      title: 'Engaging Researchers with Data IG',
      description:
        'The motivation behind this group is to build social bridges that enable open sharing and re-use of data, a goal that is fully aligned with the RDA mission. To achieve cultural change, researchers, who are the key stakeholders involved in data production and re-use, must be engaged with the topics of data management and sharing. The activities of this group will help increase engagement with diverse research communities across institutions, disciplines, and specialties.',
      uuid_domain: '04DFE4A5; 5CB3D8C8',
      domains: 'Social Sciences; Computer and information sciences ',
      url: 'https://www.rd-alliance.org/groups/engaging-researchers-data-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00058357',
      title: 'ESIP/RDA Earth, Space, and Environmental Sciences IG',
      description:
        'This Interest Group started with the BOF specific to EarthCube held at the RDA P10 meeting in September 2017 in Montreal. Results from that session showed strong interest in intenational collaboration for Earth, space, and environmental infrastructure concerns that are currently be addressed in RDA across all the sciences and external to RDA across many geographically oriented efforts. Our charter was submitted and approved in 2018 and we have participated in every plenary (just about) since then.',
      uuid_domain: '51DE8B93',
      domains: 'Earth and related environmental sciences',
      url: 'https://www.rd-alliance.org/groups/esiprda-earth-space-and-environmental-sciences-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:77DBE0D8',
      title: 'Ethics and Social Aspects of Data IG',
      description:
        'Topics of interest include the kinds/types of data that can be archived and reused and under what circumstances; education of researchers, research respondents, administrators, ethics bodies; gray and difficult areas of research that create new challenges for data management ("dangerous data", legacy data, retrospective analyses, medical humanities, wellness/lifestyle data); developing policies and practices that encourage appropriate data sharing yet protect researchers and their research respondents; obligations to and impacts on families, communities, and societies; the ethics of reuse.',
      uuid_domain: '0191D876; 04DFE4A5',
      domains: 'Philosophy, ethics and religion; Social sciences',
      url: 'https://www.rd-alliance.org/groups/ethics-and-social-aspects-data/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:D9AFA369',
      title: 'Evaluation of Research IG',
      description:
        'The evolution of the evaluation of research from being mostly bibliographic index-based is now recognized to be indispensable to enable Open Science. In the same way that Open Science promotes the open sharing of FAIR data and other research outputs, evaluators must also value and consider these outputs as part of the wider research evaluation framework. The RDA is an appropriate forum for addressing the evolving requirements of research evaluation as they relate to Open Science practices. RDA’s reach across the international community, including research organisations and funders, can help to facilitate and align a global discussion of research evaluation, drawing on data experts from a range of domains. The Interest Group "Evaluation of Research" organises the discussion on the subject in the RDA, in particular as it relates to data, and also in relation to RDA activities on research software.',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/evaluation-research-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:365CAED9',
      title: 'FAIR Digital Object Fabric IG',
      description:
        'The Data Fabric IG (DFIG) identified that working with data in the many scientific labs and most probably also in other areas such as industry and governance is highly inefficient and too costly. Excellent scientists working on date intensive science tasks are forced to spend about 75% of their time to manage, find, combine and curate data. What a waste of time and capacity. The DFIG is therefore looking at the data creation and consumption cycle to identify opportunities to optimize the work with data, to place current RDA activities in the overall landscape, to look what other rcommunities are doing in this area and to foster testing and adoption of RDA outputs. The goal of DFIG finally is to identify common components and define their characteristics and services that can be used across boundaries in such a way that they can be combined to solve a variety of data scenarios such as replicating data in federations, developing virtual research environments, and automating regular data management tasks. Much important work is being done on data publishing and citation, but DFIG believes that we need to start at early moments in the "Data Fabrics" in the labs to organize, document and manage data professionally if we want to meet the requirements of the coming decades.',
      uuid_domain: 'AD232C46',
      domains:
        'Electrical engineering, electronic engineering, information engineering',
      url: 'https://www.rd-alliance.org/group/FAIR-digital-object-fabric-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00076085',
      title: 'FAIR for Machine Learning (FAIR4ML) IG',
      description:
        'This Interest Group will enable community members to discuss the various aspects of FAIR as applied to Machine Learning, looking both at domain specific and domain-agnostic use cases, and creating task forces and working groups as needed for specific guidance documents, recommendations, definitions and technical specification to that effect. The overall aim is to foster collaborations among researchers and developers who are interested in making machine learning (data, models, workflows, etc.) FAIR, along with those who contribute to the infrastructure and policies that support this. It will work closely with other FAIR RDA Groups (such as the FAIR for Research Software Working Group), as machine learning combines aspects of data and software, but is distinctly different from both.',
      uuid_domain: '337D6D04; 51DE8B93; 29CE1D1A; 27BE021B; BD52C16D; D17D26A9',
      domains:
        'Health sciences; Earth and related environmental sciences; Physical sciences; Agricultural sciences; Materials engineering; Biological sciences',
      url: 'https://www.rd-alliance.org/groups/fair-machine-learning-fair4ml-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:EE9A0F0F',
      title: 'FAIR Instrument Data IG',
      description: 'FAIR Instrument Data IG',
      uuid_domain: '18792041; 285F97D3; 95093901; 27BE021B',
      domains:
        'Natural Sciences; Engineering and Technology; Medical and Health Sciences; Agricultural Sciences',
      url: 'https://www.rd-alliance.org/groups/fair-instrument-data-ig',
      status: 'Pending Submission',
      sub_status: 'Not Found',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00074820',
      title: 'FAIR Principles for Research Hardware',
      description:
        'In this group, we would like to build on previous work (Miljković, Trisovic, & Peer, 2021) and aim at defining FAIR principles for research hardware. We will follow the example of the FAIR4RS WG: Our work will focus on unique characteristics of hardware in relation to existing FAIR principles for data and software. We will emphasise the importance of research hardware documentation, available technology, knowledge and components (or lack thereof), and specific demands for hardware licensing. Also, complex dependencies to other hardware and software components will be discussed.',
      uuid_domain: '285F97D3',
      domains: 'Engineering and technology',
      url: 'https://www.rd-alliance.org/groups/fair-principles-research-hardware',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00058100',
      title: 'Federated Identity Management IG',
      description:
        'The interest group considers as its main task to discuss and propose solutions for the problems that are experienced by research infrastructures that need FIM services in order to operate their facilities and to serve their user communities. This agrees with the RDA ideal of a bottom-up approach where the data-practioners, in this case organised in thematic research infrastructures, are the major driving force. Past experience has taught us that solutions are required on managerial, operational, legal and technological planes, which means that representation also of enabling organizations and software producers is needed.',
      uuid_domain: '5CB3D8C8; 945CF903',
      domains: 'Computer and information sciences; Systems engineering',
      url: 'https://www.rd-alliance.org/groups/federated-identity-management-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00056636',
      title: 'From Observational Data to Information IG',
      description:
        'Our aim is to advance shared understanding of the relationship between data and information, primarily in the context of environmental research infrastructures for observational data and semantic information about observed environments. While commonly used, the terms data and information are poorly understood. Typically understood as the values organized in rows and columns, in reality there are observational data, experimental data, simulation data. There are feature, trend, geospatial data sets. There are primary data, secondary data, derivative data, operational data, metadata. Furthermore, we increasingly speak of mining information from data and transferring information into knowledge. However, what mined information is and how information is represented and recorded in research infrastructures remains obscure. Knowledge is even more complex. There is a need to clarify what data, information and possibly knowledge are, and how these concepts relate in the research infrastructure context. We provide a platform to advance this subject matter.',
      uuid_domain: '2581C431',
      domains: 'Natural Sciences',
      url: 'https://www.rd-alliance.org/groups/observational-data-information-ig',
      status: 'Withdrawn',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:56E77ED5',
      title: 'Geospatial IG',
      description:
        'The Geospatial Interest Group is a domain oriented interest group to coordinate and build synergies on topics related to geospatial data. Though there has been lot of developments and advances in geo data collection through mobile communications, sensor platforms, spatial search, and pervasive computing but still, the inter-disciplinary research needed to transform raw data into useful intelligence, to improve the planet\'s environmental, economic and societal well being, remains constrained by a range of barriers - disciplinary, organisational, historical, and a non-existent or non-rigorous approach to quantifying uncertainty in collected datasets.',
      uuid_domain: 'D17D26A9; 285F97D3',
      domains: 'Biological sciences; Engineering and Technology',
      url: 'https://www.rd-alliance.org/groups/geospatial-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00064798',
      title: 'Global Open Research Commons IG',
      description:
        'The Interest Group will provide a neutral place where people have conversations about Open Research Commons. It will function in a similar vein to the funders forum – space will be given to raise topics of mutual interest, track trends and reach consensus on priorities. The Group will work to reach a shared understanding of what a “Commons” is in the research data space; what functionality, coverage and characteristics does such an initiative require and how can this be coordinated at a global level? The IG Chairs will also proactively look outside the RDA community to connect with parallel initiatives in other spaces, whether in national / regional contexts or in other fora such as the OECD, G7 Open Science Working Group, UN’s Expert Advisory Group on a Data Revolution for Sustainable Development, CODATA, GO-FAIR and others. Recognising the broad scope, we will focus initially on Data Commons and extend to Open Science Commons as work progresses.',
      uuid_domain: '04DFE4A5; 5CB3D8C8',
      domains: 'Social Sciences; Computer and information sciences ',
      url: 'https://www.rd-alliance.org/groups/global-open-research-commons-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00050642',
      title: 'Global Water Information IG',
      description:
        'The proposed Global Water Information Interest Group (GWIIG) will serve as a platform leading to formation of RDA working group; as a venue for communication among RDA WGs and IGs focused on both technical eInfrastructure aspects (e.g. brokering; metadata and catalogs, dynamic data citation) and on related research domains (e.g. geosciences, agriculture, biodiversity); and as a coordination mechanism across a wide group of water information stakeholders, in particular those not previously involved in the OGC/WMO water standardization work.',
      uuid_domain: '2581C431',
      domains: 'Natural Sciences',
      url: 'https://www.rd-alliance.org/groups/global-water-information-interest-group-0/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00061552',
      title: 'GO FAIR Liaison IG',
      description: 'GO FAIR Liaison IG',
      uuid_domain: '285F97D3',
      domains: 'Engineering and technology',
      url: 'https://www.rd-alliance.org/groups/go-fair-liaison-ig',
      status: 'Not Found',
      sub_status: 'Not yet endorsed',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00050708',
      title: 'Health Data Interest Group',
      description:
        'The proposed Interest Group on “Health Data” (HD-IG) is a long-term initiative in the framework of RDA. It follows a rather successful BoF Session during the 6th RDA Plenary Meeting in Paris, which was attended by over 35 researchers and professionals from diverse backgrounds, who discussed several relevant issues, expressed significant interest in forming the proposed Interest Group, and helped shape its focus as presented here. The Interest Group will fill a gap in the RDA subject map formed by its current WGs and IGs, as at the moment, there is no RDA group focusing on the intricacies of Health Data, especially as it relates to privacy and security issues in Healthcare. Establishment of this IG will also enrich the set of communities involved in and contributing to RDA, as there are several professions as well as research disciplines that revolve around Health Data.',
      uuid_domain: '95093901',
      domains: 'Medical and health sciences',
      url: 'https://www.rd-alliance.org/groups/health-data/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00058721',
      title: 'IG for Surveying Open Data Practices',
      description:
        'The IG was established to convene interested parties to explore interest in and feasibility of promoting a coordinated approach to the development and analysis of open data sharing surveys. The IG is interested in the potential of harnessing the insights from survey data to inform policy and practice.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/ig-surveying-open-data-practices',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00055599',
      title: 'International Indigenous Data Sovereignty IG',
      description:
        'The goals of the International Indigenous Data Sovereignty Interest Group are clearly aligned with the RDA mission of creating a global community to develop and adopt infrastructure that promotes data-sharing, data-driven research, and data use. Those of us already involved in the national-level networks are strong advocates for data-driven research and data use, and are also working in varied ways to build data capabilities beyond academic institutions, so as to benefit Indigenous communities. Through more effective collaboration, we seek to provide a highly visible international platform for ID-Sov that integrates and leverages existing ID-sov groups to create new opportunities for research and outreach. We also seek to attract new stakeholders beyond our current networks, including researchers, data users and indigenous communities. To that end all three existing ID-Sov networks have developed strong relationships with Indigenous stakeholders including tribes, Non Governmental Organisations, and Indigenous policy institutes, and researchers.',
      uuid_domain: '14BAB0C3; 04DFE4A5',
      domains: 'Political science; Social sciences',
      url: 'https://www.rd-alliance.org/groups/international-indigenous-data-sovereignty-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00058354',
      title: 'Research Data Architectures in Research Institutions IG',
      description:
        'The Research Data Architectures in Research Institutions Interest Group is primarily concerned with technical architectures for managing research data within universities and other multi-disciplinary research institutions. It provides insight into the approaches being taken to the development and operation of such architectures and their success or otherwise in enabling good practice.',
      uuid_domain: '5CB3D8C8; 285F97D3',
      domains: 'Computer and information sciences; Engineering and technology',
      url: 'https://www.rd-alliance.org/groups/research-data-architectures-research-institutions-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:DE7DDA2D',
      title: 'Libraries for Research Data IG',
      description:
        'Critically, libraries must ensure that they are interoperable with domain data centres and other RDM infrastructures elsewhere. RDA is an important venue whereby the libraries/institutions can interact with other communities including the Domain Repositories Interest Group, the Metadata Working Group, and the Data Publishing Interest Group and bring back best practices developed elsewhere to the library community. In addition, libraries have traditional strengths that they can contribute to RDAs mission of interoperability. Libraries have a long history in terms of collaboration and developing interoperable solutions across multiple domains (e.g. OAI-PMH). They act as a bridge across disciplines and can help to identify commonalities across fields. In addition, IG will actively engage with other RDA groups or form working groups, including Education and Training as well as the Long Tail for Research Data, to ensure there are no redundancies and our work is complementary.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/libraries-research-data/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:6171CD0D',
      title: 'Life Science Data Infrastructures IG',
      description:
        'The Life Science Data Infrastructures Interest Group is formed to serve as a bridge between life science data infrastructures in different regions of the world and relevant RDA Interest Groups, including both specific subtopics of the life sciences such as agricultural data, marine data, structural biology, toxicogenomics, as well as generic topics that can/should be applied in the life sciences such as big data analysis, federated identity management, and data publishing.',
      uuid_domain: '2581C431; 95093901; 27BE021B',
      domains:
        'Natural Sciences; Medical and Health Sciences; Agricultural Sciences',
      url: 'https://www.rd-alliance.org/groups/life-science-data-infrastructures-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00055091',
      title: 'Linguistics Data IG',
      description:
        'The Linguistics Data Interest Group plans to identify, prioritize, and get to work on data challenges across the Linguistics domain. As a first step, this new group will focus P10 time on developing the discipline-wide adoption of common standards for data citation and attribution, and to improve research data management training in the discipline. In our parlance citation refers to the practice of identifying the source of linguistic data, and attribution refers to mechanisms for assessing the intellectual and academic value of creating, managing, storing, sharing, and citing primary data.',
      uuid_domain: '6DC9618F',
      domains: 'Humanities',
      url: 'https://www.rd-alliance.org/groups/linguistics-data-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:B9E72F18',
      title: 'Long tail of research data IG',
      description:
        'The long tail of research data is defined loosely as those data that do not fall within the category of big data. The aim of this interest group is to share practices and discuss strategies for improving the management and visibility of this type of data. Interest group members have identified a number of issues they wish to pursue in the context of this Interest Group',
      uuid_domain: '5CB3D8C8; C1E4C81A; 04DFE4A5',
      domains:
        'Computer and information sciences; Educational sciences; Social sciences',
      url: 'https://www.rd-alliance.org/groups/long-tail-research-data-ig/',
      status: '',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00054284',
      title: 'Mapping the Landscape IG',
      description:
        'This group was partially informed by the RDA Atlas of Knowledge (AOK) and the RDA Technical Advisory Board (TAB) Landscape Overview Group (LOG) mapping exercises, though in contrast to this activity, the proposed MOL IG will focus on activities eternally to RDA and at a higher organizational level.',
      uuid_domain: '5CB3D8C8; 285F97D3',
      domains: 'Computer and information sciences; Engineering and technology',
      url: 'https://www.rd-alliance.org/groups/mapping-landscape-ig',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:E33AA193',
      title: 'Metadata IG',
      description:
        'The Metadata IG will concern itself with all aspects of metadata for research data. In particular, it will attempt to coordinate the efforts of the WGs concerned with metadata to produce a coherent approach to metadata covering metadata modalities of description, restriction, navigation, provenance, preservation and the use of metadata for the purposes discovery, contextualisation, validation, analytical processing, simulation, visualisation and interoperation. It will also liaise with the other WGs especially Data Foundation and Terminology, PIDs, Standardisation of data categories and codes and Data Citation. This IG activity relates to data management policies and plans of research organisations and researchers, and to policies and standards of research funders and of research communities which may or may not be official standards.',
      uuid_domain: '04DFE4A5; 18792041; 285F97D3; 95093901; 27BE021B; 6DC9618F',
      domains:
        'Social Sciences; Natural Sciences; Engineering and Technology; Medical and Health Sciences; Agricultural Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/metadata-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00047656',
      title: 'National Data Services IG',
      description:
        'The interest group aims to identify shared concerns and jointly address them through a variety of independent projects, collaborations, or working groups.',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/national-data-services/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:7776TAG0',
      title: 'National PID Strategies Interest Group',
      description:
        'The National PID Strategies Interest Group aims to:Facilitate information exchange between those developing and/or delivering national PID strategies. Facilitate engagement between developers of national PID strategies and international PID providers such as ORCID, DataCite and CrossRef. Collaboratively develop the value proposition for national PID strategies overall as well as its component parts (such as grant identifiers, person identifiers, organisation identifiers) that can be reused/adapted by the community. Collect case studies of national PID strategies from countries across the globe. Maintain outputs (the Guide, Checklist and Case Studies) produced by the National PID Strategies WG',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/national-pid-strategies-interest-group',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00063572',
      title: 'Open Science Graphs for FAIR Data IG',
      description:
        'The goal of the Open Science Graphs Interest Group (OSG IG) is to build on the outcomes and broaden the challenges of the Data Description Registry Interoperability (DDRI) and Scholarly Link Exchange (Scholix) RDA Working Groups to investigate the open issues and identify solutions towards achieving interoperability between services and information models of Open Science Graph initiatives. The aim is to improve FAIRness of research data, and more generally FAIR*-ness of science, by enabling the smooth exchange of the interlinked metadata overlay required to access research data at the meta-level of the discovery-for-citation/monitoring and at the thematic level of the discovery-for-reuse. Such “FAIR-ness” and “interlinked-ness” provide strong support for research integrity and research innovation which in turn underpin significant social environmental and economic benefits.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/open-science-graphs-fair-data-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00056746',
      title:
        'Physical Samples and Collections in the Research Data Ecosystem IG',
      description:
        'Physical samples are a basic element for reference, study, and experimentation in research. Tests and analysis are conducted directly on samples, such as biological specimens, rock or mineral specimens, soil or sediment cores, plants and seeds, water quality samples, archaeological artefacts, or DNA and human tissue samples because they represent a wider population or a larger context. Other physical objects, such as maps or analogue images are also direct objects of study, and, if digitized, may become a source of digital data. There is an urgent need for better integrating these physical objects into the digital research data ecosystem, both in a global and in an interdisciplinary context to support search, retrieval, analysis, reuse, preservation and scientific reproducibility. This group aims to facilitate cross-domain exchange and convergence on key issues related to the digital representation of physical samples and collections, including but not limited to use of globally unique and persistent identifiers for samples to support unambiguous citation and linking of information in distributed data systems and with publications, metadata standards for documenting samples and collections and for landing pages, access policies, and best practices for sample and collection catalog, including a broad range of issues from interoperability to persistence.',
      uuid_domain: '51DE8B93; D17D26A9',
      domains: 'Earth and related environmental sciences; Biological sciences',
      url: 'https://www.rd-alliance.org/groups/physical-samples-and-collections-research-data-ecosystem-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:D46F1575',
      title: 'PID IG',
      description:
        'The PID IG will foster working groups to address specific topics, and in particular to address and define emerging PID use cases in the domain of data, and whether the research community would benefit from a global open identifiers for persons, data objects, organizations, grants, etc. Where applicable the PID-IG will collaborate with existing RDA working groups, or it will establish new working groups based on priority areas as identified at RDA plenaries.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/pid-interest-group/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00054902',
      title: 'Preservation Tools, Techniques, and Policies',
      description:
        'The Preservation Tools, Techniques, and Policies (PTTP) IG provides a forum to bring together domain researchers, data and informatics experts, and policy specialists to discuss such issues as: What data/software/artifacts/documentation (hereafter referred to as “knowledge products”) should be preserved for sharing, re-use, and reproducibility for a given research domain?For other domains? What tools are available for researchers to preserve these elements in a manner that does not obstruct or hinder their research? What are the strengths and weaknesses of these tools? Are there common features that could allow tools from one domain to be re-used elsewhere? Are there tools that archives/repositories could provide that could make preservation much easier for researchers? What are the longer-term development goals of each of these tools? What preservation policies exist, imposed by government agencies, publishers, or other actors? How are they changing? How are they implemented? What are their strengths and weaknesses? How can preservation policies be implemented in a way that aids research both now and in the future? How does this depend on the tools provided?',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/preservation-tools-techniques-and-policies',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00068877',
      title: 'Professionalising Data Stewardship IG',
      description:
        'The Interest Group will focus on exchanging good practices, initiatives and projects that could help research organisations in professionalising data stewardship. This Interest Group will liaise with communities, initiatives and projects outside RDA, thus fostering synergies. To our knowledge, there currently is no network that connects and bridges between the various initiatives and projects on professionalising data stewardship.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/professionalising-data-stewardship-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:CCE7DAE9',
      title: 'Psychological Data IG',
      description:
        'Aligning with RDA’s mission, the purpose of the Psychology RDA Interest Group (IG) is to raise awareness of the importance of data sharing, and to provide support with respect to the technical skills needed for FAIR data sharing within the Psychology community. This IG brings together Psychology researchers with an interest in open, transparent, and reproducible research methods and practices. The IG will link with the equivalent IGs/Working Groups in cogent disciplines (e.g., Neuroscience) and with other organisations such as the UK Reproducibility Network (UKRN), the European Open Science Cloud (EOSC), the Software Sustainability Institute (SSI), Open Life Sciences, and The Carpentries. This IG will facilitate the sharing of effective practice, expertise, and computational tools that support FAIR data sharing.',
      uuid_domain: '04DFE4A5; 6DC9618F',
      domains: 'Social Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/psychological-data-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:BC322F0C',
      title: 'Quality of Urban Life IG',
      description:
        'In 2007 the world’s population became more urban than rural according to the United Nations. Urban Quality of Life (QoL) is the general well-being of individual and societies living in cities. As there is a growing number of the world\'s population moving into cities there is increasing importance for the need for urban QoL indicators that can benchmark and enable comparative analysis in and between cities so that the social, environmental, economic and cultural dimensions can utlimately be improved. This RDA interest group is being set up to contribute to this challenge by identifying a minimum set of interoperable open access datasets across the social, environmental, economic and cultural domains that can be used to build comparable indicators of Urban Quality of Life (QoL) in a global setting.',
      uuid_domain: '04DFE4A5; 51DE8B93; 3CD09AF9; 6DC9618F',
      domains:
        'Social sciences; Earth and related environmental sciences; Economics and business; Humanities',
      url: 'https://www.rd-alliance.org/groups/urban-quality-life-indicators/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00066028',
      title: 'RDA for the Sustainable Development Goals IG',
      description:
        'The Sustainable Development Goals (SDGs) are 17 global goals, with 169 associated targets, which came into effect in January 2016 and will continue to guide UN policy and funding until 2030. Progress on the UN\'s 17 Sustainable Development Goals requires broad collaboration within the global data community, as well as nuanced understanding of the barriers for developing information infrastructures. Interoperability of data remains a barrier to collecting, storing, merging, and analyzing data for monitoring SDG metrics effectively - and improving data interoperability may both enhance monitoring, as well as help to enable and support progress towards achieving the SDGs. Achieving interoperable data to advance the SDGs will require best practices, recommendations, technologies, and support of capacity building - which is in direct alignment with many of RDA’s ongoing and upcoming outputs, recommendations, interest group, and working group activities.',
      uuid_domain: '14BAB0C3; 055BCEA8',
      domains: 'Political science; Social and economic geography',
      url: 'https://www.rd-alliance.org/groups/rda-sustainable-development-goals-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00050796',
      title: 'RDA Privacy Implications of Research Data Sets IG',
      description:
        'This IG starter out as a Working Group, to explore issues related to scientific research data sets that contains human subject information, as well as related datasets that have the potential to be combined in a way that can expose private information. The goal of the group is to develop a framework for how researchers and repositories should appropriately manage human-subject datasets, to develop a metadata set to describe the privacy-related aspects of research datasets, and to build awareness of the privacy implications of research data sharing. While privacy is related to the ethical, legal and data publishing issues surrounding data management of which privacy is a part, this working group is focused specifically on privacy-related concerns.',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/rdaniso-privacy-implications-research-data-sets-wg/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:A2B1EB4B',
      title: 'RDA-COVID19-Clinical',
      description: 'RDA-COVID19-Clinical',
      uuid_domain: '',
      domains: '',
      url: '',
      status: 'Recognised & Endorsed',
      sub_status: 'WGs Maintaining deliverables (maintenance group)',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:7098A359',
      title: 'RDA/CODATA Legal Interoperability IG',
      description:
        'The proposed Research Data Alliance – CODATA Working Group on Legal Interoperability of Research Data (RDA-CODATA WG), will be established to address and promote the following objectives: Define legal interoperability of research data and articulate why it is important for data interoperability and reuse. Document and analyze up to four case studies in the areas of geoscience, biodiversity research, social sciences, and humanities of legal interoperability solutions in interdisciplinary and international contexts. Develop and publish core principles and guidelines of best practices through which legal interoperability can be achieved, and link to related information resources online. Work with key stakeholder groups to get the core principles and guidelines of best practices adopted. Generally promote better understanding and greater use by the stakeholder groups in the research community of the agreed approaches to legal interoperability of research data, focused on highlighting and enabling better integration and reuse of such data.',
      uuid_domain: '1FD22581; D17D26A9; 04DFE4A5; 6DC9618F',
      domains: 'Law; Biological sciences; Social sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/rdacodata-legal-interoperability-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:F9AE2231',
      title: 'RDA/CODATA Materials Data, Infrastructure & Interoperability IG',
      description:
        'The development of advanced materials inherently rests on access to a distributed materials infrastructure and materials research data to fuel discovery and innovation. RDA aims to accelerate and facilitate research data sharing and exchange. Similarly, CODATA works to strengthen international science for the benefit of society by promoting improved scientific and technical data management and use. Given these complementary missions, this RDA IG and the CODATA TG will work together under the following statement in support of the exchange of material data.',
      uuid_domain: 'BD52C16D',
      domains: 'Materials engineering',
      url: 'https://www.rd-alliance.org/groups/rdacodata-materials-data-infrastructure-interoperability-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:E670622F',
      title: 'RDA/WDS Certification of Digital Repositories IG',
      description:
        'The Interest Group will build on previous work in the area of certification. It will deliver the global overview and the necessary recommendations and requirements that allow the effective implementation of certification of digital repositories on a national, European and even global level.',
      uuid_domain: '5CB3D8C8; 3CD09AF9',
      domains: 'Computer and information sciences; Economics and business',
      url: 'https://www.rd-alliance.org/groups/rdawds-certification-digital-repositories-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00031943',
      title: 'RDA/WDS Publishing Data Cost Recovery for Data Centres IG',
      description:
        'General services to publish data are not available and the necessary editorial process leading to quality assured and efficiently usable data requires resources to be quantified. At present, there is an imbalance between the capacities and functionality of existing data centres and data repositories and the global production of scientific data. Budgets of data centres generally cover a precise scope, mostly data production of the host institution. The WG will supply cost estimates and elaborate a business model to compensate for additional costs of publishing data in an open access environment.',
      uuid_domain: '5CB3D8C8; 3CD09AF9',
      domains: 'Computer and information sciences; Economics and business',
      url: 'https://www.rd-alliance.org/groups/rdawds-publishing-data-cost-recovery-data-centres/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:B8D3DA0D',
      title: 'RDA/WDS Publishing Data IG',
      description:
        'The Publishing Data Interest Group brings together all stakeholders involved in publishing research data including researchers, discipline specific and institutional data repositories, academic publishers, funders and service providers. Every effort will be made to get a good representation from related international programmes, their working groups and other private or institutional activities involved in this area. We will build on existing resources, reports and other shared experiences from the different stakeholders and will nurture more specific and targeted working groups addressing practical aspects in publishing research data. As such, the Publishing Data Interest Group can be regarded as a broad and inclusive forum for interested individuals to contribute to and test, validate and promote the findings of the Working Groups. In particular we plan to address the implementation of workflows for publishing data and therefore help establish appropriate supporting infrastructure.',
      uuid_domain: '5CB3D8C8; B44F0E9D',
      domains: 'Computer and information sciences; Media and communications',
      url: 'https://www.rd-alliance.org/groups/rdawds-publishing-data-ig/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00046536',
      title: 'Repository Platforms for Research Data IG',
      description:
        'Research data repositories are at the heart of data sharing as they provide platforms to acquire, store, archive, publish, curate, preserve, and access data. Thus, the major goal of the Repository Platforms for Research Data (RPRD) Interest Group (IG) is to improve the usability and technical capabilities of repository platforms. To achieve this, the RPRD IG invites members of the research data community to collect usage experiences, define requirements, evaluate implementations, and identify limitations of current solutions in a cooperation of repository users, managers, providers, and developers. Possible outputs of our efforts might be recommendations, knowledge collections, or new working groups to investigate identified issues.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/repository-platforms-research-data/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00045120',
      title: 'Reproducibility IG',
      description:
        'This interest group seeks to advance and enable reproducibility in research based on or producing datasets that require code. Our goals are to build bridges with the many RDA external efforts addressing reproducibility, doing so in coordination with the other RDA Working and Interest Groups where appropriate. Our efforts may also produce Working Groups that can develop recommendations and solutions.',
      uuid_domain: '5CB3D8C8; 285F97D3',
      domains: 'Computer and information sciences; Engineering and technology',
      url: 'https://www.rd-alliance.org/groups/reproducibility-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00061116',
      title: 'Research Data Management in Engineering IG',
      description:
        'The aims of the Interest Group "Research Data Management in Engineering" (IG RDM4Eng) are changing the culture of handling data, creating awareness and bridging (sub-) communities and existing initiatives, which often exist only within a research group. Moreover, the IG will provide a platform for developing consensus on RDM best practices for engineering and to find convincing arguments for engineers in academia and industry to introduce or to improve RDM practices in their workflows.',
      uuid_domain: '285F97D3',
      domains: 'Engineering and Technology',
      url: 'https://www.rd-alliance.org/groups/research-data-management-engineering-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:37AABB08',
      title:
        'Research data needs of the Photon and Neutron Science community IG',
      description:
        'This Interest Group will focus on data related issues of science applications associated with large scale source facilities, including: synchrotron x-ray sources, free-electron laser x-ray sources, reactor and spallation neutron sources, muon sources, large electron microscope, NMR and high-powered laser facilities, which are used typically for investigations into the structure of matter at micro or nano scale.',
      uuid_domain: 'FF2F40FC; 285F97D3',
      domains: 'Nano technology; Engineering and technology',
      url: 'https://www.rd-alliance.org/groups/research-data-needs-photon-and-neutron-science-community/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00061537',
      title:
        'Research Funders and Stakeholders on Open Research and Data Management Policies and Practices IG',
      description:
        'Research funders have been participating in the RDA since the beginning, first through the Funders’ Forum, and then they began to propose Bird of a Feathers sessions in which funders from around the globe bring subjects that they wish to discuss publicly among themselves and on which they want to gather input from the RDA community. The aim of the proposed Interest Group is to provide a sustainable venue for these discussions. Funders are important RDA stakeholders, and the IG would substantiate their engagement with RDA and be fully aligned with the RDA principles of openness, harmonization and being community-driven. It would be a significant value-added contribution to the RDA community as a vehicle for open discussion of policy-driven topics.',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/research-funders-and-stakeholders-open-research-and-data-management-policies-and-practices-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00068876',
      title: 'Science Communication For Research Data',
      description: 'Science communication for research data',
      uuid_domain: '5CB3D8C8; B44F0E9D',
      domains: 'Computer and information sciences; Media and communications',
      url: 'https://www.rd-alliance.org/groups/science-communication-research-data',
      status: 'Pending Submission',
      sub_status: 'Not yet endorsed',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00072299',
      title: 'Sensitive Data Interest Group',
      description:
        'We propose developing a shared understanding of sensitive data assets by running a BoF session at RDA VP16. The aim of this BoF is to share experiences working with sensitive data in a research context, identify the key challenges in this area, and to find others who may be facing similar challenges. If there is sufficient community interest, we aim to create a Working Group or Interest Group on this topic. We envisage this group as part of a global Community of Practice',
      uuid_domain: '04DFE4A5; 27BE021B; 285F97D3; 95093901; 27BE021B; 6DC9618F',
      domains:
        'Social Sciences; Natural Sciences; Engineering and Technology; Medical and Health Sciences; Agricultural Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/sensitive-data-interest-group',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00057240',
      title: 'Sharing Rewards and Credit (SHARC) IG',
      description:
        'SHARC is a recognised and endorsed interest group within RDA (Research Data Alliance). It is an interdisciplinary group seeking to unpack and improve crediting and rewarding mechanisms for open science activities and in particular, for the data/resources sharing process. It aims to provide guidance for researchers and recommendations to all key actors of the academic recognition ecosystem.',
      uuid_domain: '04DFE4A5; 2581C431; 95093901',
      domains: 'Social Sciences; Natural Sciences; Medical and Health Sciences',
      url: 'https://www.rd-alliance.org/groups/sharing-rewards-and-credit-sharc-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00074541',
      title:
        'Skills and training curriculums to support FAIR research software IG',
      description:
        'This group aims to highlight the importance of this work to ensure research software skills are included in ongoing work, to highlight current initiatives in research software training that can provide the basis for skills identification, and to learn from complementary efforts on FAIR data. This will be based on discussions at a Birds of a Feather (BoF) session held during the RDA Plenary in November 2021.',
      uuid_domain: '5CB3D8C8; C1E4C81A; 04DFE4A5',
      domains:
        'Computer and information sciences; Educational sciences; Social sciences',
      url: 'https://www.rd-alliance.org/groups/skills-and-training-curriculums-support-fair-research-software-ig',
      status: 'Pending Submission',
      sub_status: 'Not yet endorsed',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:9AE26198',
      title: 'Small Unmanned Aircraft Systems\' Data IG',
      description:
        'This interest group therefore seeks to explore and publish (via the RDA community based model), some best practices as regards the handling of sUAS captured sensor and flight data. By publishing such, after a broad, cross-community engagement process, it is hoped and expected that such will see adoption by both those already using sUAS for scientific work those just beginning to explore their possibilities. They will therefore address the 3 concerns laid out above, with the associated positive consequences for the scientific community. These outcomes also align directly with the RDA’s Vision and Mission focus, namely, promoting the open sharing of data.',
      uuid_domain: '285F97D3',
      domains: 'Engineering and Technology',
      url: 'https://www.rd-alliance.org/groups/small-unmanned-aircraft-systems%E2%80%99-data-ig',
      status: 'Recognised & Endorsed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00063042',
      title: 'Social Dynamics of Data Interoperability IG',
      description:
        'Social Dynamics are some of the most difficult challenges to address. Currently there is a limited body of work on how to address these challenges in a systematic way. In keeping with the mission of the RDA, the focus of this group is to focus on what is required to build the social bridges that enable open sharing and re-use of data. The focus of this interest group is to identify opportunities for the development of systematic approaches to address the key social challenges and to build a corpus of knowledge on building and operating interoperable information infrastructures.',
      uuid_domain: '5CB3D8C8; 04DFE4A5',
      domains: 'Computer and information sciences; Social sciences ',
      url: 'https://www.rd-alliance.org/groups/social-dynamics-data-interoperability-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00052861',
      title: 'Weather, climate and air quality IG',
      description:
        'In a field where the amount and the data sources increase exponentially, it becomes critical to find efficient solutions at a community level to address problems such as storage, indexing, metadata, sharing, or analysis. The global objectives of this Interest Group will be to explore and discuss the challenges for management, efficient analysis and dissemination of large and diverse datasets generated by the weather, climate and air quality communities. These communities follow one of the main ideas of data sharing of RDA as most of the datasets used are completely open and freely available. Most of the concepts and problems that this IG aims to address correspond to classic RDA issues (metadata, data standards, efficient sharing, etc...) but as these communities already have rules and policies structured in terms of standards and data portals, they need some advanced community specific solution to these issues.',
      uuid_domain: '2581C431',
      domains: 'Natural sciences',
      url: 'https://www.rd-alliance.org/groups/weather-climate-and-air-quality-ig',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00061540',
      title: 'Social Science Research Data IG',
      description:
        'This new SSH interest group will begin by helping to coordinate communications across the various current RDA groups of interest to our disciplines and to provide a place for our members to share solutions and concerns with others in our fields. These groups include the FAIRSharing and others noted by Braukmann in the “RDA Overview for the Social Sciences”[1]. We will also seek input and coordinate with the external SSH community leaders and organizations such as CESSDA, DDI Alliance, IASSIST, ICPSR, IFDO and WDS. We will be open and inclusive seeking to use this group to connect the various organizations working to promote SSH data sharing. While this new interest group will certainly be a coordinating group, we also aim to produce new RDA Working Groups to help provide solutions to challenges in our SSH domains. Given the complexity of SSHRD, we feel that the initial focus of our interest group should be very focused on defining working groups of immediate need to our communities. We foresee that to implement FAIR in our disciplines we need to engage all stakeholders: funders, producers, service providers, users; and as a new interest group we want to prioritise on three specific areas focused on the Social Science and Humanities research data communities.',
      uuid_domain: '04DFE4A5; 6DC9618F',
      domains: 'Social Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/social-science-research-data-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00056578',
      title: 'Software Source Code IG',
      description:
        'This interest group will provide a forum to discuss issues on management, sharing, discovery, archival and provenance of software source code. It will pay special attention to source code that generates research data and plays an important role in scientific publications.',
      uuid_domain: '285F97D3; 5CB3D8C8',
      domains: 'Engineering and Technology; Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/software-source-code-ig',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00002243',
      title: 'Structural Biology IG',
      description:
        'Structural Biology (SB) is concerned with the determination of the three-dimensional (3D) structures of individual biomacromolecules (proteins and nucleic acids), and with those of complexes and higher order structures formed by association of these individual components. The ultimate goal of SB is to understand the mode of action of these biological nano machines, based on their static 3D structures, their dynamic characteristics, and the ways in which they interact both with other macromolecules and with small ligands such as drugs and agrochemicals. SB contributes to society by supporting a range of applications including drug design, crop improvement, and engineering of enzymes of industrial significance.',
      uuid_domain: 'D17D26A9; FF2F40FC; 27BE021B',
      domains: 'Biological sciences; Nano technology; Agricultural sciences',
      url: 'https://www.rd-alliance.org/groups/structural-biology-ig/',
      status: 'Completed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00073937',
      title: 'Structure of Information',
      description:
        'In his classical paper More is different, P.W. Anderson (1972) discusses the hierarchical levels of nature. Each level is made of and obeys the laws of its constituents from one level below. All levels are connected by quantitative relations to their lower and higher hierarchical neighbor which links the physical entities of all hierarchies. In simple cases, when the constitutive relations are linear or conceptually readily apparent, we may deduce exact ab initio equations providing material properties as a function of its constituents. In most cases, however, we encounter the formation of complex systems with emergent properties. Typically, there is a branch of science for each level of complexity, since, for each complexity level, there seem to be objects for which it is appropriate and fitting to build up vocabulary for the respective levels of description leading to formation of disciplinary language. It is the central idea of causal emergence (Hoel 2017) that on each level defining a major discipline there is an optimal degree of coarse graining to define those objects in such a way that causality becomes maximal between them.',
      uuid_domain: '04DFE4A5; 18792041; 6DC9618F',
      domains: 'Social Sciences; Natural Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/structure-information',
      status: 'Pending Submission',
      sub_status: 'Not yet endorsed',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:7776TAG1',
      title:
        'Understanding and Capturing the Uptake of Digital Research Infrastructure IG',
      description:
        'Understanding and Capturing the Uptake of Digital Research Infrastructure IG',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/uptake-digital-research-infrastructure-ig/',
      status: 'Pending Submission',
      sub_status: 'Not Found',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00051565',
      title: 'Virtual Research Environment IG (VRE-IG)',
      description:
        'The VRE IG will aim to act as a longer-term organization responsible for tracking and contributing to the evolution of VRE/SG/VL technologies, particularly as they relate to data access. It will also seek to engage with those seeking to make use of these online technologies in an effort to identify the necessary technical aspects, social and community building practices, required skills, as well as governance issues and best practice required to support a more coordinated approach to the development of the collaborative environments that enable data sharing and in situ online processing.',
      uuid_domain: '04DFE4A5; 18792041; 285F97D3; 95093901; 27BE021B; 6DC9618F',
      domains:
        'Social Sciences; Natural Sciences; Engineering and Technology; Medical and Health Sciences; Agricultural Sciences; Humanities',
      url: 'https://www.rd-alliance.org/groups/vre-ig/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00047826',
      title: 'Vocabulary Services IG',
      description:
        'The Vocabulary Service Interest Group (VSIG) seeks to develop community-based recommendations on approaches to publication of controlled vocabularies on the web. Community standard controlled vocabularies are used in metadata annotation and labelling data files to solve problems of ambiguity associated with data markup and also enabling records to be interpreted by computers. This opens up data sets to a whole world of possibilities for computer aided manipulation, distribution and long term reuse. The recommendations of the Vocabulary Service Interest Group will address the needs of research communities for using controlled vocabularies published on the web. The Interest Group aims to represent all stakeholders involved in the controlled vocabulary lifecycle in research domains: content producers; maintainers; and consumers. Discussions topics will include, but are not necessarily be limited to: vocabulary representation; reuse; curation; and interlinking or mapping. These discussions will allow the Interest Group to propose solutions allowing the cross-domain use of vocabularies, including mapping relationships between domains. This Interest Group will help to promote good practices by producers and consumers of controlled vocabularies. The Interest Group will develop a timeline for activities as they form.',
      uuid_domain: '5CB3D8C8',
      domains: 'Computer and information sciences',
      url: 'https://www.rd-alliance.org/groups/vocabulary-services-interest-group/',
      status: 'Recognised & Endorsed',
      sub_status: 'IG Established',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:00076528',
      title: 'Working with PIDS in Tools IG',
      description:
        'Lack of interoperability between tools/e-infrastructures presents a significant barrier to streamlining processes throughout the research lifecycle. These gaps prevent the comprehensive collection and incorporation of research data and metadata into the research record captured during the active research phase. Furthermore, it limits the scope for passing this data and metadata on to data repositories, thus undermining FAIR data principles and reproducibility. This IG is proposed as: A place to address interoperability between tools/e-infrastructures, leveraging PID and metadata infrastructure. A platform for research-supporting service providers and PID/open infrastructure organizations to outline use cases, explore challenges, and pool resources to provide reference and guidance to chart ways forward. A forum for dissecting the interoperability challenges through discussion of concrete case studies involving application of PIDS to tools in multiple communities of practice.',
      uuid_domain: '18792041; 285F97D3; 95093901; 27BE021B',
      domains:
        'Natural Sciences; Engineering and Technology; Medical and Health Sciences; Agricultural Sciences',
      url: 'https://www.rd-alliance.org/groups/working-pids-tools-ig',
      status: 'Recognised & Endorsed',
      sub_status: '',
      last_update: null,
    },
    {
      uuid_interestGroup: 'rda_graph:35b557aa',
      title: 'Research Tools and Data Curation Workflows IG',
      description:
        'We wish for our IG to explore the intersection between research tools and data curation workflows, in order to demystify the pain points that emerge in onboarding, adoption, and processes, and especially in communication between research tool providers and institutions, which then prevent successful utilisation of these tools.\nWe aim to develop guidelines and facilitate a shared language between research data managers and research tool providers around data curation, and by grounding ourselves in a universal lifecycle model, we hope to formalise institutional RDM approaches and their resulting research tool needs and requirements. We aim for this work to help inform the research tool selection and adoption process through a well articulated statement of purpose.\nWe believe our work would address concrete practical issues that cause points of friction in institutional research infrastructures, which are constantly increasing in complexity and becoming essential to all research disciplines, requiring great understanding of researcher and curator needs.\n',
      uuid_domain: '',
      domains: 'Domain Agnostic',
      url: 'https://rda.md-staging.site/groups/research-tools-and-data-curation-workflows-ig/activity',
      status: 'Recognised and Endorsed',
      sub_status: 'Established',
      last_update: '2025-07-10 09:50:36.094751+00',
    },
    {
      uuid_interestGroup: 'rda_graph:cc5f282f',
      title: 'Salmon Research and Monitoring IG',
      description:
        'An RDA Interest Group dedicated to the salmon research and monitoring community which will aim to accelerate the uptake of interoperable methods and data from research, management, and monitoring, so as to empower the community to further develop the mechanistic understanding of what drives salmon declines, and importantly develop methods to counter the declines. We will focus on these factors through the development of Working Groups aligned with the RDA methodology, 12 &#8211; 18 month focussed efforts to tackle specific challenges in adherence to FAIR principles in line with the RDA mission.\n',
      uuid_domain: '',
      domains: 'Natural Sciences',
      url: 'https://rda.md-staging.site/groups/salmon-research-and-monitoring-ig/activity',
      status: 'Recognised and Endorsed',
      sub_status: 'Established',
      last_update: '2025-07-10 09:50:36.094751+00',
    },
    {
      uuid_interestGroup: 'rda_graph:e409d4cb',
      title: 'Small Unmanned Aircraft Systems’ Data IG',
      description:
        'Update: In the immediate much of our disucssions are happening on this Slack channel, to join see this link\nSmall Unmanned Aircraft Systems (sUAS) are rapidly becoming important tools for data capture across many Scientific domains, as well as within commercial industry.  sUAS have the potential to transform how data are captured in many arenas by, offering higher temporal and spatial resolutions, with less impact on the environments being monitored, and access to new locations and parameters.  In many cases these advantages are further accompanied by lowered costs and increased human safety during data capture.   \n \nAs a new technology, however, there are currently no industry-wide accepted best practices for sUAS sensor and flight data handling and management.  There are many reasons for why such would be beneficial but 3 of particular note include: \n\nThe creation of standards would lower the barrier to entry and  innovation in terms of what might be monitored with sUAS, by reducing the number of unknowns a new user faces and providing working examples to serve as guides.\nWith no common goal standards to build to, the development of mature tools for sUAS captured data processing and fusion (with sUAS and other data sources) is currently hampered.  As a consequence, each use case generally develops a unique custom pipeline that only sees one-time use.  \nsUAS captured data is &#8211; for the most part &#8211; not being managed according to data stewardship best practices, such as would ensure the data is FAIR, as articulated by Force11 (Findable, Accessible, Interoperable, and Re-usable).   \n\nThis interest group therefore seeks to explore and publish (via the RDA community based model), some best practices as regards the handling of sUAS captured sensor and flight data.  By publishing such, after a broad, cross-community engagement process, it is hoped and expected that such will see adoption by both those already using sUAS for scientific work those just beginning to explore their possibilities.  They will therefore address the 3 concerns laid out above, with the associated positive consequences for the scientific community. These outcomes also align directly with the RDA’s Vision and Mission focus, namely, promoting the open sharing of data.\n',
      uuid_domain: '',
      domains: '',
      url: 'https://rda.md-staging.site/groups/small-unmanned-aircraft-systems-data-ig/activity',
      status: 'Recognised and Endorsed',
      sub_status: 'Established',
      last_update: '2025-07-10 09:50:36.094751+00',
    },
  ]

  return interestGroups.map(
    ig =>
      ({
        label: ig.title,
        value: ig.uuid_interestGroup,
        secondarySearch: ig.description,
        // description: ig.description,
      } satisfies DataSource),
  )
}
