import { DataSource } from "@/types/datasource.interface";

export default async function fetchKeywords(): Promise<DataSource[]> {
  const keywords = [
    {
      uuid_keyword: "rda_graph:MK4W0001",
      keyword: "Research Data Administration",
    },
    { uuid_keyword: "rda_graph:MK4W0002", keyword: "Adoption" },
    { uuid_keyword: "rda_graph:MK4W0003", keyword: "Agrisemantics" },
    { uuid_keyword: "rda_graph:MK4W0004", keyword: "Algorithms" },
    { uuid_keyword: "rda_graph:MK4W0005", keyword: "Alumni" },
    { uuid_keyword: "rda_graph:MK4W0007", keyword: "Annotation" },
    { uuid_keyword: "rda_graph:MK4W0008", keyword: "application profiles" },
    { uuid_keyword: "rda_graph:MK4W0009", keyword: "Archives" },
    {
      uuid_keyword: "rda_graph:MK4W0010",
      keyword: "Artificial Intelligence",
    },
    { uuid_keyword: "rda_graph:MK4W0011", keyword: "Attribution" },
    { uuid_keyword: "rda_graph:MK4W0012", keyword: "Auditing" },
    { uuid_keyword: "rda_graph:MK4W0013", keyword: "Availability" },
    { uuid_keyword: "rda_graph:MK4W0014", keyword: "Best Practices" },
    { uuid_keyword: "rda_graph:MK4W0015", keyword: "Bibliometrics" },
    { uuid_keyword: "rda_graph:MK4W0017", keyword: "Birds of a Feather" },
    { uuid_keyword: "rda_graph:MK4W0018", keyword: "Blockchain" },
    { uuid_keyword: "rda_graph:MK4W0019", keyword: "Business Models" },
    { uuid_keyword: "rda_graph:MK4W0020", keyword: "Catalogues" },
    { uuid_keyword: "rda_graph:MK4W0021", keyword: "Categorization" },
    { uuid_keyword: "rda_graph:MK4W0022", keyword: "Certification" },
    { uuid_keyword: "rda_graph:MK4W0023", keyword: "Citation" },
    { uuid_keyword: "rda_graph:MK4W0024", keyword: "Cloud Computing" },
    { uuid_keyword: "rda_graph:MK4W0025", keyword: "CODATA" },
    { uuid_keyword: "rda_graph:MK4W0026", keyword: "Collaboration" },
    { uuid_keyword: "rda_graph:MK4W0027", keyword: "Communication" },
    {
      uuid_keyword: "rda_graph:MK4W0028",
      keyword: "Communities of Practice",
    },
    { uuid_keyword: "rda_graph:MK4W0029", keyword: "Computing" },
    { uuid_keyword: "rda_graph:MK4W0030", keyword: "conceptual model" },
    {
      uuid_keyword: "rda_graph:MK4W0031",
      keyword: "connecting to end-user communities",
    },
    { uuid_keyword: "rda_graph:MK4W0032", keyword: "CoreTrustSeal" },
    { uuid_keyword: "rda_graph:MK4W0033", keyword: "COVID-19" },
    { uuid_keyword: "rda_graph:MK4W0034", keyword: "COVID-19 guidelines" },
    {
      uuid_keyword: "rda_graph:MK4W0035",
      keyword: "COVID-19 recommendations",
    },
    {
      uuid_keyword: "rda_graph:MK4W0036",
      keyword: "cross-institutional adoption",
    },
    { uuid_keyword: "rda_graph:MK4W0037", keyword: "Data Access" },
    { uuid_keyword: "rda_graph:MK4W0038", keyword: "Data Centres" },
    { uuid_keyword: "rda_graph:MK4W0039", keyword: "Data Citation" },
    { uuid_keyword: "rda_graph:MK4W0040", keyword: "Data Commons" },
    { uuid_keyword: "rda_graph:MK4W0041", keyword: "Data Conservation" },
    { uuid_keyword: "rda_graph:MK4W0042", keyword: "Data Cost Recovery" },
    { uuid_keyword: "rda_graph:MK4W0043", keyword: "Data Cultures" },
    { uuid_keyword: "rda_graph:MK4W0044", keyword: "Data Curation" },
    { uuid_keyword: "rda_graph:MK4W0045", keyword: "Data Discovery" },
    { uuid_keyword: "rda_graph:MK4W0046", keyword: "Data Domains" },
    { uuid_keyword: "rda_graph:MK4W0047", keyword: "Data Fabric" },
    { uuid_keyword: "rda_graph:MK4W0048", keyword: "Data Fitness for use" },
    { uuid_keyword: "rda_graph:MK4W0049", keyword: "Data Foundation" },
    { uuid_keyword: "rda_graph:MK4W0050", keyword: "Data Governance" },
    { uuid_keyword: "rda_graph:MK4W0051", keyword: "Data Handling" },
    { uuid_keyword: "rda_graph:MK4W0052", keyword: "Data Infrastructure" },
    { uuid_keyword: "rda_graph:MK4W0053", keyword: "Data Integration" },
    { uuid_keyword: "rda_graph:MK4W0054", keyword: "Data Interoperability" },
    { uuid_keyword: "rda_graph:MK4W0055", keyword: "Data Licensing" },
    { uuid_keyword: "rda_graph:MK4W0056", keyword: "Data Life Cycle" },
    { uuid_keyword: "rda_graph:MK4W0057", keyword: "Data Management" },
    { uuid_keyword: "rda_graph:MK4W0058", keyword: "Data Management Plan" },
    { uuid_keyword: "rda_graph:MK4W0059", keyword: "Data Maturity" },
    { uuid_keyword: "rda_graph:MK4W0060", keyword: "Data Metrics" },
    { uuid_keyword: "rda_graph:MK4W0061", keyword: "Data Modeling" },
    { uuid_keyword: "rda_graph:MK4W0062", keyword: "Data Ownership" },
    { uuid_keyword: "rda_graph:MK4W0063", keyword: "Data Packages" },
    { uuid_keyword: "rda_graph:MK4W0065", keyword: "Data Preservation" },
    { uuid_keyword: "rda_graph:MK4W0066", keyword: "Data Protection" },
    { uuid_keyword: "rda_graph:MK4W0067", keyword: "Data Publishing" },
    {
      uuid_keyword: "rda_graph:MK4W0069",
      keyword: "Data Repository Platforms",
    },
    { uuid_keyword: "rda_graph:MK4W0070", keyword: "Data Rescue" },
    { uuid_keyword: "rda_graph:MK4W0071", keyword: "Data Science" },
    { uuid_keyword: "rda_graph:MK4W0072", keyword: "Data Seal of Approval" },
    { uuid_keyword: "rda_graph:MK4W0073", keyword: "Data Search" },
    { uuid_keyword: "rda_graph:MK4W0076", keyword: "Data Sharing" },
    { uuid_keyword: "rda_graph:MK4W0077", keyword: "Data Simulation" },
    { uuid_keyword: "rda_graph:MK4W0078", keyword: "Data Solutions" },
    { uuid_keyword: "rda_graph:MK4W0079", keyword: "Data Sovereignty" },
    { uuid_keyword: "rda_graph:MK4W0080", keyword: "Data Stewardship" },
    { uuid_keyword: "rda_graph:MK4W0082", keyword: "Data Transfer" },
    { uuid_keyword: "rda_graph:MK4W0083", keyword: "Data Typing" },
    { uuid_keyword: "rda_graph:MK4W0084", keyword: "Data Versioning" },
    { uuid_keyword: "rda_graph:MK4W0087", keyword: "Databases" },
    { uuid_keyword: "rda_graph:MK4W0088", keyword: "Datasets" },
    { uuid_keyword: "rda_graph:MK4W0089", keyword: "Dataverse" },
    { uuid_keyword: "rda_graph:MK4W0090", keyword: "Data principles" },
    { uuid_keyword: "rda_graph:MK4W0091", keyword: "Digital Collections" },
    { uuid_keyword: "rda_graph:MK4W0092", keyword: "Digital Object" },
    {
      uuid_keyword: "rda_graph:MK4W0093",
      keyword: "Digital Object Identifiers",
    },
    {
      uuid_keyword: "rda_graph:MK4W0094",
      keyword: "Digital Object Management",
    },
    { uuid_keyword: "rda_graph:MK4W0095", keyword: "Digital Repositories" },
    {
      uuid_keyword: "rda_graph:MK4W0099",
      keyword: "Early Career Researchers",
    },
    { uuid_keyword: "rda_graph:MK4W0100", keyword: "Education" },
    { uuid_keyword: "rda_graph:MK4W0101", keyword: "Elections" },
    { uuid_keyword: "rda_graph:MK4W0102", keyword: "ELIXIR" },
    { uuid_keyword: "rda_graph:MK4W0103", keyword: "EOSC" },
    { uuid_keyword: "rda_graph:MK4W0104", keyword: "ESFRI" },
    { uuid_keyword: "rda_graph:MK4W0105", keyword: "Ethics" },
    { uuid_keyword: "rda_graph:MK4W0106", keyword: "Ethnography" },
    { uuid_keyword: "rda_graph:MK4W0107", keyword: "FAIR assessment tools" },
    { uuid_keyword: "rda_graph:MK4W0108", keyword: "FAIR Data" },
    { uuid_keyword: "rda_graph:MK4W0109", keyword: "FAIR Indicators" },
    { uuid_keyword: "rda_graph:MK4W0110", keyword: "FAIR Indikatoren" },
    { uuid_keyword: "rda_graph:MK4W0111", keyword: "FAIR Principles" },
    { uuid_keyword: "rda_graph:MK4W0112", keyword: "Federated Databases" },
    { uuid_keyword: "rda_graph:MK4W0113", keyword: "File Formats" },
    { uuid_keyword: "rda_graph:MK4W0115", keyword: "Funding" },
    { uuid_keyword: "rda_graph:MK4W0116", keyword: "GIS" },
    { uuid_keyword: "rda_graph:MK4W0117", keyword: "GORC" },
    { uuid_keyword: "rda_graph:MK4W0118", keyword: "Governance" },
    { uuid_keyword: "rda_graph:MK4W0119", keyword: "Guidelines" },
    { uuid_keyword: "rda_graph:MK4W0120", keyword: "Handles" },
    { uuid_keyword: "rda_graph:MK4W0121", keyword: "ICSU World Data System" },
    { uuid_keyword: "rda_graph:MK4W0122", keyword: "Indexing" },
    { uuid_keyword: "rda_graph:MK4W0124", keyword: "Information sharing" },
    { uuid_keyword: "rda_graph:MK4W0127", keyword: "Integrity" },
    { uuid_keyword: "rda_graph:MK4W0128", keyword: "Intellectual Property" },
    { uuid_keyword: "rda_graph:MK4W0129", keyword: "Interoperability" },
    { uuid_keyword: "rda_graph:MK4W0130", keyword: "Interoperability Model" },
    { uuid_keyword: "rda_graph:MK4W0134", keyword: "learning resources" },
    { uuid_keyword: "rda_graph:MK4W0135", keyword: "Libraries" },
    {
      uuid_keyword: "rda_graph:MK4W0136",
      keyword: "Linguistics Data Citation",
    },
    { uuid_keyword: "rda_graph:MK4W0137", keyword: "Linguistics Dataset" },
    { uuid_keyword: "rda_graph:MK4W0138", keyword: "Linked Data" },
    { uuid_keyword: "rda_graph:MK4W0140", keyword: "long tail data" },
    { uuid_keyword: "rda_graph:MK4W0141", keyword: "Long-term Preservation" },
    { uuid_keyword: "rda_graph:MK4W0142", keyword: "Machine Learning" },
    { uuid_keyword: "rda_graph:MK4W0143", keyword: "machine-actionable" },
    { uuid_keyword: "rda_graph:MK4W0144", keyword: "Marketing" },
    { uuid_keyword: "rda_graph:MK4W0145", keyword: "Materials" },
    { uuid_keyword: "rda_graph:MK4W0146", keyword: "Metadata" },
    { uuid_keyword: "rda_graph:MK4W0147", keyword: "metadata schemas" },
    { uuid_keyword: "rda_graph:MK4W0148", keyword: "minimal metadata" },
    {
      uuid_keyword: "rda_graph:MK4W0149",
      keyword: "Models of data stewardship",
    },
    { uuid_keyword: "rda_graph:MK4W0150", keyword: "Multidisciplinary" },
    { uuid_keyword: "rda_graph:MK4W0151", keyword: "Networks" },
    { uuid_keyword: "rda_graph:MK4W0154", keyword: "Ontology" },
    { uuid_keyword: "rda_graph:MK4W0155", keyword: "Open Access" },
    { uuid_keyword: "rda_graph:MK4W0157", keyword: "Open Science" },
    { uuid_keyword: "rda_graph:MK4W0158", keyword: "OpenAIRE" },
    {
      uuid_keyword: "rda_graph:MK4W0159",
      keyword: "Organisational Membership",
    },
    { uuid_keyword: "rda_graph:MK4W0160", keyword: "Persistent Identifiers" },
    {
      uuid_keyword: "rda_graph:MK4W0161",
      keyword: "PID Kernel Information Profile",
    },
    { uuid_keyword: "rda_graph:MK4W0162", keyword: "Platforms" },
    { uuid_keyword: "rda_graph:MK4W0163", keyword: "Policy" },
    { uuid_keyword: "rda_graph:MK4W0164", keyword: "Policy Making" },
    { uuid_keyword: "rda_graph:MK4W0165", keyword: "Practical Policy" },
    { uuid_keyword: "rda_graph:MK4W0167", keyword: "Processes" },
    { uuid_keyword: "rda_graph:MK4W0168", keyword: "Product Maintenance" },
    {
      uuid_keyword: "rda_graph:MK4W0169",
      keyword: "Professional Societites",
    },
    {
      uuid_keyword: "rda_graph:MK4W0170",
      keyword: "Professionalising Data Stewardship",
    },
    { uuid_keyword: "rda_graph:MK4W0171", keyword: "Provenance" },
    { uuid_keyword: "rda_graph:MK4W0172", keyword: "Provenance tracking" },
    { uuid_keyword: "rda_graph:MK4W0173", keyword: "Publication" },
    { uuid_keyword: "rda_graph:MK4W0174", keyword: "Publishing" },
    { uuid_keyword: "rda_graph:MK4W0175", keyword: "Publishing Workflows" },
    { uuid_keyword: "rda_graph:MK4W0176", keyword: "RDA" },
    { uuid_keyword: "rda_graph:MK4W0177", keyword: "RDA Europe" },
    { uuid_keyword: "rda_graph:MK4W0178", keyword: "RDA National" },
    { uuid_keyword: "rda_graph:MK4W0179", keyword: "RDA Outputs" },
    { uuid_keyword: "rda_graph:MK4W0180", keyword: "RDA Policy" },
    { uuid_keyword: "rda_graph:MK4W0181", keyword: "RDA Recommendation" },
    { uuid_keyword: "rda_graph:MK4W0182", keyword: "RDA Report" },
    { uuid_keyword: "rda_graph:MK4W0183", keyword: "RDA Secretariat" },
    { uuid_keyword: "rda_graph:MK4W0184", keyword: "RDA Supporting Output" },
    {
      uuid_keyword: "rda_graph:MK4W0185",
      keyword: "CODATA Data Science Journal",
    },
    { uuid_keyword: "rda_graph:MK4W0186", keyword: "CFP" },
    { uuid_keyword: "rda_graph:MK4W0188", keyword: "Recommendation" },
    { uuid_keyword: "rda_graph:MK4W0189", keyword: "Records Management" },
    { uuid_keyword: "rda_graph:MK4W0190", keyword: "Registries" },
    { uuid_keyword: "rda_graph:MK4W0191", keyword: "Replication" },
    { uuid_keyword: "rda_graph:MK4W0192", keyword: "Reporting" },
    { uuid_keyword: "rda_graph:MK4W0193", keyword: "Repositories" },
    {
      uuid_keyword: "rda_graph:MK4W0194",
      keyword: "Repository Interoperability",
    },
    { uuid_keyword: "rda_graph:MK4W0195", keyword: "Reproducability" },
    { uuid_keyword: "rda_graph:MK4W0196", keyword: "Reproducible Research" },
    { uuid_keyword: "rda_graph:MK4W0197", keyword: "Research Data" },
    { uuid_keyword: "rda_graph:MK4W0198", keyword: "Research Data Alliance" },
    {
      uuid_keyword: "rda_graph:MK4W0199",
      keyword: "Research Data Management",
    },
    {
      uuid_keyword: "rda_graph:MK4W0200",
      keyword: "Research Data Switchboard",
    },
    { uuid_keyword: "rda_graph:MK4W0201", keyword: "Research Hardware" },
    { uuid_keyword: "rda_graph:MK4W0202", keyword: "research output" },
    { uuid_keyword: "rda_graph:MK4W0203", keyword: "Research Platforms" },
    { uuid_keyword: "rda_graph:MK4W0204", keyword: "Research Software" },
    { uuid_keyword: "rda_graph:MK4W0205", keyword: "Resource Management" },
    { uuid_keyword: "rda_graph:MK4W0206", keyword: "Schemas" },
    {
      uuid_keyword: "rda_graph:MK4W0207",
      keyword: "Scholarly Communication",
    },
    { uuid_keyword: "rda_graph:MK4W0208", keyword: "Scholix" },
    { uuid_keyword: "rda_graph:MK4W0209", keyword: "School" },
    { uuid_keyword: "rda_graph:MK4W0210", keyword: "Semantics" },
    { uuid_keyword: "rda_graph:MK4W0211", keyword: "Skills" },
    { uuid_keyword: "rda_graph:MK4W0212", keyword: "Software" },
    { uuid_keyword: "rda_graph:MK4W0213", keyword: "SSHOC" },
    { uuid_keyword: "rda_graph:MK4W0214", keyword: "Standardization" },
    { uuid_keyword: "rda_graph:MK4W0215", keyword: "Standardized metadata" },
    { uuid_keyword: "rda_graph:MK4W0216", keyword: "Standards" },
    { uuid_keyword: "rda_graph:MK4W0217", keyword: "Statistics" },
    { uuid_keyword: "rda_graph:MK4W0218", keyword: "Storage" },
    { uuid_keyword: "rda_graph:MK4W0219", keyword: "Structural Biology" },
    { uuid_keyword: "rda_graph:MK4W0220", keyword: "Survey" },
    { uuid_keyword: "rda_graph:MK4W0221", keyword: "Survey Data" },
    { uuid_keyword: "rda_graph:MK4W0224", keyword: "TAB" },
    { uuid_keyword: "rda_graph:MK4W0225", keyword: "Taxonomies" },
    { uuid_keyword: "rda_graph:MK4W0227", keyword: "Terminology" },
    { uuid_keyword: "rda_graph:MK4W0228", keyword: "thematic data service" },
    {
      uuid_keyword: "rda_graph:MK4W0229",
      keyword: "Thematic textual analysis",
    },
    { uuid_keyword: "rda_graph:MK4W0231", keyword: "training materials" },
    { uuid_keyword: "rda_graph:MK4W0232", keyword: "training portals" },
    { uuid_keyword: "rda_graph:MK4W0233", keyword: "Trust" },
    { uuid_keyword: "rda_graph:MK4W0234", keyword: "Tutorial" },
    { uuid_keyword: "rda_graph:MK4W0235", keyword: "Typing" },
    { uuid_keyword: "rda_graph:MK4W0236", keyword: "Typologies" },
    { uuid_keyword: "rda_graph:MK4W0238", keyword: "Validation" },
    { uuid_keyword: "rda_graph:MK4W0239", keyword: "versioning procedures" },
    {
      uuid_keyword: "rda_graph:MK4W0240",
      keyword: "Virtual Research Environments",
    },
    { uuid_keyword: "rda_graph:MK4W0241", keyword: "Vocabularies" },
    { uuid_keyword: "rda_graph:MK4W0242", keyword: "wheat research" },
    { uuid_keyword: "rda_graph:MK4W0243", keyword: "Work Attribution" },
    { uuid_keyword: "rda_graph:MK4W0244", keyword: "Workflows" },
    { uuid_keyword: "rda_graph:MK4W0245", keyword: "Data Mobility" },
    { uuid_keyword: "rda_graph:MK4W0246", keyword: "Architectures" },
    { uuid_keyword: "rda_graph:MK4W0247", keyword: "Distributed Databases" },
    { uuid_keyword: "rda_graph:MK4W0249", keyword: "Data Mining" },
    { uuid_keyword: "rda_graph:MK4W0250", keyword: "Data Dissemination" },
    { uuid_keyword: "rda_graph:MK4W0251", keyword: "Observation Data" },
    { uuid_keyword: "rda_graph:MK4W0252", keyword: "Transparency" },
    { uuid_keyword: "rda_graph:MK4W0253", keyword: "Data Flows" },
    { uuid_keyword: "rda_graph:MK4W0254", keyword: "Engagement" },
    { uuid_keyword: "rda_graph:MK4W0255", keyword: "Methodology" },
    { uuid_keyword: "rda_graph:MK4W0256", keyword: "Citizen Science" },
    { uuid_keyword: "rda_graph:MK4W0257", keyword: "Data Granularity" },
    { uuid_keyword: "rda_graph:MK4W0258", keyword: "Networks" },
    { uuid_keyword: "rda_graph:MK4W0259", keyword: "Genomics" },
    { uuid_keyword: "rda_graph:MK4W0260", keyword: "Biodiversity" },
    { uuid_keyword: "rda_graph:MK4W0261", keyword: "Conservation" },
    { uuid_keyword: "rda_graph:MK4W0262", keyword: "Computer Science" },
    { uuid_keyword: "rda_graph:MK4W0263", keyword: "Biomedical Research" },
    { uuid_keyword: "rda_graph:MK4W0264", keyword: "Clinical Practice" },
    { uuid_keyword: "rda_graph:MK4W0265", keyword: "Biochemistry" },
    { uuid_keyword: "rda_graph:MK4W0266", keyword: "Biotechnology" },
    { uuid_keyword: "rda_graph:MK4W0267", keyword: "Agriculture" },
    { uuid_keyword: "rda_graph:MK4W0268", keyword: "Food" },
    { uuid_keyword: "rda_graph:MK4W0269", keyword: "Environment" },
    { uuid_keyword: "rda_graph:MK4W0270", keyword: "Bioinformatics" },
    { uuid_keyword: "rda_graph:MK4W0272", keyword: "Rare Disease" },
    { uuid_keyword: "rda_graph:MK4W0273", keyword: "Data Analysis" },
    { uuid_keyword: "rda_graph:MK4W0274", keyword: "Computational advances" },
    { uuid_keyword: "rda_graph:MK4W0275", keyword: "Molecular Medicine" },
    { uuid_keyword: "rda_graph:MK4W0276", keyword: "Biochemistry" },
    { uuid_keyword: "rda_graph:MK4W0277", keyword: "Health Data" },
    { uuid_keyword: "rda_graph:MK4W0278", keyword: "Digital Humanities" },
    { uuid_keyword: "rda_graph:MK4W0279", keyword: "European" },
    { uuid_keyword: "rda_graph:MK4W0281", keyword: "Data Spaces" },
    { uuid_keyword: "rda_graph:MK4W0282", keyword: "Data Ecosystems" },
    { uuid_keyword: "rda_graph:MK4W0283", keyword: "Documentation" },
    { uuid_keyword: "rda_graph:MK4W0284", keyword: "Code" },
    { uuid_keyword: "rda_graph:MK4W0288", keyword: "Big Health Data" },
    {
      uuid_keyword: "rda_graph:MK4W0289",
      keyword: "Volumetric Imaging Services",
    },
    { uuid_keyword: "rda_graph:MK4W0290", keyword: "Research Data Graph" },
    { uuid_keyword: "rda_graph:MK4W0291", keyword: "Policy Frameworks" },
    { uuid_keyword: "rda_graph:MK4W0292", keyword: "Management Frameworks" },
    { uuid_keyword: "rda_graph:MK4W0293", keyword: "Conceptual Frameworks" },
    { uuid_keyword: "rda_graph:MK4W0294", keyword: "Data Frameworks" },
    {
      uuid_keyword: "rda_graph:MK4W0295",
      keyword: "Interoperability Frameworks",
    },
    {
      uuid_keyword: "rda_graph:MK4W0296",
      keyword: "Collaboration Frameworks",
    },
    { uuid_keyword: "rda_graph:MK4W0297", keyword: "Workflow Frameworks" },
    { uuid_keyword: "rda_graph:MK4W0298", keyword: "Research Frameworks" },
    { uuid_keyword: "rda_graph:MK4W0299", keyword: "Open Research Data" },
    { uuid_keyword: "rda_graph:MK4W0300", keyword: "Personal Privacy" },
    { uuid_keyword: "rda_graph:MK4W0301", keyword: "Privacy Tags" },
    { uuid_keyword: "rda_graph:MK4W0302", keyword: "Data Privacy" },
    {
      uuid_keyword: "rda_graph:MK4W0303",
      keyword: "Sustainability Strategy",
    },
    { uuid_keyword: "rda_graph:MK4W0304", keyword: "Charter Template" },
    { uuid_keyword: "rda_graph:MK4W0305", keyword: "Group Template" },
    { uuid_keyword: "rda_graph:MK4W0306", keyword: "Mathematical Tools" },
    {
      uuid_keyword: "rda_graph:MK4W0307",
      keyword: "Interdisciplinary Research",
    },
    { uuid_keyword: "rda_graph:MK4W0308", keyword: "Innovative Practices" },
    { uuid_keyword: "rda_graph:MK4W0309", keyword: "Case Studies" },
    { uuid_keyword: "rda_graph:MK4W0310", keyword: "Data Reuse" },
    { uuid_keyword: "rda_tiger:MRAZ1XIFCAC1PHS9OQ9B7", keyword: "Test Tag" },
    { uuid_keyword: "rda_tiger:INLTZLX0N8BI1TESZHFXC", keyword: "FAIR" },
    {
      uuid_keyword: "rda_tiger:XFEXKW9R110GC8NV9AGMW",
      keyword: "Condensed-matter physics",
    },
    {
      uuid_keyword: "rda_tiger:035L323AR2D22HI2E3DLU",
      keyword: "Chemical physics of solids",
    },
    {
      uuid_keyword: "rda_tiger:UVKPUL7IL6VVSV90KWCRA",
      keyword: "vocabularies",
    },
    {
      uuid_keyword: "rda_tiger:J3CQW3P3EI5C7WM3BTPX0",
      keyword: "Ontologies",
    },
    {
      uuid_keyword: "rda_tiger:O95Z6MVFO1QFG7Q38HEEX",
      keyword: "FAIR-IMPACT",
    },
    {
      uuid_keyword: "rda_tiger:L31KKQ4EFOLZ72I8RRUH5",
      keyword: "semantic artefacts",
    },
  ];

  return keywords.map(
    (keyword) =>
      ({
        label: keyword.keyword,
        value: keyword.uuid_keyword,
      } satisfies DataSource)
  );
}
