// This is the main entry point for the Hypothesis client in the host page
// and the sidebar application.
//
// The same boot script is used for both entry points so that the browser
// already has it cached when it encounters the reference in the sidebar
// application.
import { bootHypothesisClient, bootSidebarApp } from "./boot";
import type { AnnotatorConfig, SidebarAppConfig } from "./boot";
import { isBrowserSupported } from "./browser-check";
import { getExtensionId, hasExtensionConfig } from "./browser-extension-utils";
import { parseJsonConfig } from "./parse-json-config";
import { processUrlTemplate } from "./url-template";

/**
 * @NOTE Should find a way to generate manifest file with cache-busted URLs.
 */
const manifest: Record<string, string> = {
  "annotator.js": "annotator.js?fceda4",
  "annotator.js.map": "annotator.js.map?11a837",
  "sidebar.js": "sidebar.js?51aaf7",
  "sidebar.js.map": "sidebar.js.map?d212f6",
  "styles/annotator.css": "styles/annotator.css?c1d2f9",
  "styles/annotator.css.map": "styles/annotator.css.map?1ba208",
  "styles/highlights.css": "styles/highlights.css?470b72",
  "styles/highlights.css.map": "styles/highlights.css.map?f23b53",
  "styles/katex.min.css": "styles/katex.min.css?921c28",
  "styles/katex.min.css.map": "styles/katex.min.css.map?7e544d",
  "styles/pdfjs-overrides.css": "styles/pdfjs-overrides.css?c95edf",
  "styles/pdfjs-overrides.css.map": "styles/pdfjs-overrides.css.map?9b78be",
  "styles/sidebar.css": "styles/sidebar.css?ad2b5d",
  "styles/sidebar.css.map": "styles/sidebar.css.map?1f3bc6",
};

const test = __CACHE_BUSTER__;

console.log(test);

if (isBrowserSupported()) {
  const config = parseJsonConfig(document) as
    | AnnotatorConfig
    | SidebarAppConfig;
  const assetRoot = processUrlTemplate(config.assetRoot);

  // Check whether this is a mini-app (indicated by the presence of a
  // `<hypothesis-app>` element) and load the appropriate part of the client.
  /**
   * @NOTE This likely is the desktop app or something like that for RDA this will not be needed.
   * We will likely have to look if this can be scrapped easily.
   */
  if (document.querySelector("hypothesis-app")) {
    const sidebarConfig = config as SidebarAppConfig;
    bootSidebarApp(document, {
      assetRoot,
      manifest,
      apiUrl: sidebarConfig.apiUrl,
    });
  } else {
    // When the boot script is executed from the browser extension on a host
    // frame, a config generated by that specific extension is required
    const extensionId = getExtensionId();
    if (extensionId && !hasExtensionConfig(extensionId)) {
      throw new Error(
        "Could not start Hypothesis extension as configuration is missing"
      );
    }
    // nb. If new asset URLs are added here, the browser extension and
    // `hypothesis-injector.ts` need to be updated.
    const annotatorConfig = config as AnnotatorConfig;
    const notebookAppUrl = processUrlTemplate(annotatorConfig.notebookAppUrl);
    const profileAppUrl = processUrlTemplate(annotatorConfig.profileAppUrl);
    const sidebarAppUrl = processUrlTemplate(annotatorConfig.sidebarAppUrl);

    /**
     * @NOTE The manifest file is normally generated and imported.
     * The current issue is that WXT + VITE's build step doesn't let us easily import it.
     * For now this will work but it will need to be changed later.
     */
    bootHypothesisClient(document, {
      assetRoot,
      notebookAppUrl,
      profileAppUrl,
      sidebarAppUrl,
      manifest,
    });
  }
} else {
  // Show a "quiet" warning to avoid being disruptive on non-Hypothesis sites
  // that embed the client.
  //
  // In Via or when using the bookmarklet we could show something louder.
  /**
   * @NOTE Create an documentation page with documentation for this page.
   */
  console.warn(
    "The Hypothesis annotation tool is not supported in this browser. See https://web.hypothes.is/help/which-browsers-are-supported-by-hypothesis/."
  );
}
